package io.github.isysdcore.genericAutoCrud.test.generics;


import static org.hamcrest.Matchers.*;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultHandlers.print;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

import com.fasterxml.jackson.databind.ObjectMapper;
import io.github.isysdcore.genericAutoCrud.test.generics.model.TestProperties;
import io.github.isysdcore.genericAutoCrud.test.utils.UtilServiceTests;
import lombok.extern.slf4j.Slf4j;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.request.MockHttpServletRequestBuilder;
import org.springframework.util.LinkedMultiValueMap;
import org.springframework.util.MultiValueMap;

import java.lang.reflect.Field;
import java.lang.reflect.Method;
import java.util.UUID;

/**
 * Abstract integration test for V2 DTO‑based controllers.
 * <p>
 * Unlike the entity version, DTOs do not extend {@code GenericEntity} and their IDs
 * are generated by the server. This class automatically extracts the created ID
 * and uses it in subsequent tests.
 * <p>
 * Concrete subclasses only need to supply the endpoint path and a new empty DTO instance.
 *
 * @param <D> the DTO type (can be a class or a record)
 */
@Slf4j
@SpringBootTest
@AutoConfigureMockMvc
public abstract class GenericRestIntegrationDtoTests<D> implements RestIntegrationTests {

    @Autowired
    protected MockMvc mockMvc;

    @Autowired
    protected ObjectMapper objectMapper;

    @Autowired
    protected UtilServiceTests utilsServices;

    protected final String endpoint;
    protected final D dtoTemplate;
    protected D dtoInstance;
    protected String createdEntityId;       // extracted from creation response
    protected TestProperties testProperties;

    protected GenericRestIntegrationDtoTests(String endpoint, D dtoTemplate) {
        this.endpoint = endpoint;
        this.dtoTemplate = dtoTemplate;
        this.testProperties = TestProperties.builder()
                .resourceUrl(endpoint)
                .auth(false)
                .build();
    }

    @BeforeEach
    public void setUp() throws Exception {
        authenticationManagement();
        prepareNewDto();
    }

    /**
     * Fills {@link #dtoInstance} with random valid data, skipping the {@code id}
     * field because it is generated by the server.
     */
    private void prepareNewDto() {
        try {
            dtoInstance = (D) dtoTemplate.getClass().getDeclaredConstructor().newInstance();
            for (Field field : dtoTemplate.getClass().getDeclaredFields()) {
                field.setAccessible(true);
                if ("id".equals(field.getName())) {
                    continue;
                }
                try {
                    UtilServiceTests.setValueByClassType(field, dtoInstance);
                } catch (IllegalAccessException e) {
                    log.error("Failed to set field {}", field.getName(), e);
                }
            }
        } catch (Exception e) {
            throw new RuntimeException("Cannot instantiate DTO", e);
        }
    }

    /**
     * Override to perform authentication and set the token in {@link #testProperties}.
     * See {@link GenericRestIntegrationTestsImpl#authenticationManagement()} for an example.
     */
    public void authenticationManagement() throws Exception {}

    /**
     * Store a number of DTOs in the database (e.g. via a service).
     * Override in concrete tests if needed; by default it does nothing.
     */
    protected void storeEntitiesInDb(int quantity) {
        // Override if pre‑population is required
    }

    private void addAuthIfRequired(MockHttpServletRequestBuilder request) {
        if (testProperties.isAuth() &&
                testProperties.getAuthHeaderName() != null &&
                testProperties.getTokenType() != null &&
                testProperties.getAuthToken() != null) {
            request.header(testProperties.getAuthHeaderName(),
                    testProperties.getTokenType() + " " + testProperties.getAuthToken());
        }
    }

    // =================================================================
    // CRUD tests (DTO version)
    // =================================================================

    @Override
    @Test
    public void shouldCreateEntity() throws Exception {
        var request = post(testProperties.getResourceUrl())
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(dtoInstance));
        addAuthIfRequired(request);

        String response = mockMvc.perform(request)
                .andExpect(result -> {
                    int status = result.getResponse().getStatus();
                    Assertions.assertTrue(
                            status == HttpStatus.OK.value() ||
                                    status == HttpStatus.CREATED.value() ||
                                    status == HttpStatus.ACCEPTED.value(),
                            "Expected 200, 201 or 202 but got " + status);
                })
                .andExpect(jsonPath("$.id").isNotEmpty())
                .andDo(print())
                .andReturn().getResponse().getContentAsString();

        createdEntityId = objectMapper.readTree(response).get("id").asText();
    }

    @Override
    @Test
    public void shouldReturnEntity() throws Exception {
        ensureCreated();

        var request = get(testProperties.getResourceUrl() + "/{id}", createdEntityId)
                .contentType(MediaType.APPLICATION_JSON);
        addAuthIfRequired(request);

        mockMvc.perform(request)
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.id").value(createdEntityId))
                .andExpect(jsonPath("$." + getFirstFieldName()).isNotEmpty())
                .andExpect(jsonPath("$." + getSecondFieldName()).isNotEmpty())
                .andDo(print());
    }

    @Override
    @Test
    public void shouldReturnListOfEntities() throws Exception {
        MultiValueMap<String, String> params = new LinkedMultiValueMap<>();
        params.add("page", "0");
        params.add("size", "10");
        params.add("sort", "0");

        var request = get(testProperties.getResourceUrl()).params(params)
                .contentType(MediaType.APPLICATION_JSON);
        addAuthIfRequired(request);

        mockMvc.perform(request)
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.empty").value(false))
                .andExpect(jsonPath("$.totalElements").value(greaterThan(0)))
                .andDo(print());
    }

    @Override
    @Test
    public void shouldReturnListOfEntitiesWithFilter() throws Exception {
        ensureCreated();
        String fieldName = getFirstFieldName();
        Object fieldValue = getFieldValue(dtoInstance, fieldName);

        MultiValueMap<String, String> params = new LinkedMultiValueMap<>();
        params.add("page", "0");
        params.add("size", "10");
        params.add("sort", "0");
        params.add("query", fieldName + "==" + fieldValue);

        var request = get(testProperties.getResourceUrl() + "/search").params(params)
                .contentType(MediaType.APPLICATION_JSON);
        addAuthIfRequired(request);

        mockMvc.perform(request)
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.empty").value(false))
                .andExpect(jsonPath("$.totalElements").value(greaterThan(0)))
                .andDo(print());
    }

    @Override
    @Test
    public void shouldReturnNoContentWhenFilter() throws Exception {
        String fieldName = getFirstFieldName();

        MultiValueMap<String, String> params = new LinkedMultiValueMap<>();
        params.add("page", "0");
        params.add("size", "10");
        params.add("sort", "0");
        params.add("query", fieldName + "==NONEXISTENT");

        var request = get(testProperties.getResourceUrl() + "/search").params(params)
                .contentType(MediaType.APPLICATION_JSON);
        addAuthIfRequired(request);

        mockMvc.perform(request)
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.empty").value(true))
                .andExpect(jsonPath("$.totalElements").value(0))
                .andDo(print());
    }

    @Override
    @Test
    public void shouldUpdateEntity() throws Exception {
        ensureCreated();
        D before = dtoInstance;
        String firstFieldName = getFirstFieldName();
        Object oldFirst = getFieldValue(before, firstFieldName);
        String secondFieldName = getSecondFieldName();
        Object oldSecond = getFieldValue(before, secondFieldName);

        prepareNewDto(); // refresh with new random data

        var request = put(testProperties.getResourceUrl() + "/{id}", createdEntityId)
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(dtoInstance));
        addAuthIfRequired(request);

        mockMvc.perform(request)
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.id").value(createdEntityId))
                .andExpect(jsonPath("$." + firstFieldName).value(not(oldFirst)))
                .andExpect(jsonPath("$." + secondFieldName).value(not(oldSecond)))
                .andDo(print());
    }

    @Override
    @Test
    public void shouldDeleteEntity() throws Exception {
        ensureCreated();

        var request = delete(testProperties.getResourceUrl() + "/{id}", createdEntityId)
                .contentType(MediaType.APPLICATION_JSON);
        addAuthIfRequired(request);

        mockMvc.perform(request)
                .andExpect(status().isNoContent())
                .andDo(print());
    }

    @Override
    @Test
    public void shouldReturnNotFoundEntity() throws Exception {
        var request = get(testProperties.getResourceUrl() + "/{id}", UUID.randomUUID())
                .contentType(MediaType.APPLICATION_JSON);
        addAuthIfRequired(request);

        mockMvc.perform(request)
                .andExpect(status().isNotFound())
                .andDo(print());
    }

    @Override
    @Test
    public void shouldReturnNotFoundUpdateEntity() throws Exception {
        var request = put(testProperties.getResourceUrl() + "/{id}", UUID.randomUUID())
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(dtoInstance));
        addAuthIfRequired(request);

        mockMvc.perform(request)
                .andExpect(status().isNotFound())
                .andDo(print());
    }

    // =================================================================
    // Helpers
    // =================================================================

    private void ensureCreated() throws Exception {
        if (createdEntityId == null) {
            shouldCreateEntity();
        }
    }

    // =================================================================
    // Reflection helpers (record‑safe)
    // =================================================================

    private String getFirstFieldName() {
        Field[] fields = dtoTemplate.getClass().getDeclaredFields();
        return fields.length > 0 ? fields[0].getName() : "id";
    }

    private String getSecondFieldName() {
        Field[] fields = dtoTemplate.getClass().getDeclaredFields();
        return fields.length > 1 ? fields[1].getName() : "id";
    }

    /**
     * Retrieves a field value from an object, using the record's accessor method
     * if the object is a Java record, otherwise using reflective field access.
     */
    private Object getFieldValue(Object obj, String fieldName) {
        try {
            if (obj.getClass().isRecord()) {
                Method accessor = obj.getClass().getMethod(fieldName);
                return accessor.invoke(obj);
            }
            Field field = obj.getClass().getDeclaredField(fieldName);
            field.setAccessible(true);
            return field.get(obj);
        } catch (Exception e) {
            throw new RuntimeException("Cannot get value of field '" + fieldName + "'", e);
        }
    }
}