package io.github.isysdcore.genericAutoCrud.generics.nosql;

import jakarta.validation.constraints.NotNull;
import org.jspecify.annotations.NonNull;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.repository.ListCrudRepository;
import org.springframework.data.repository.NoRepositoryBean;
import org.springframework.data.repository.PagingAndSortingRepository;

import java.util.Optional;

/**
 * Generic repository contract for MongoDB entities.
 *
 * <p>This interface extends the MongoDB repository infrastructure and provides
 * standard CRUD operations, pagination, sorting, and query execution
 * capabilities for the specified entity type.</p>
 *
 * <p>Repository implementations are automatically generated by Spring Data
 * MongoDB, allowing data access operations to be performed without requiring
 * manual implementation code.</p>
 *
 * @param <ENTITY> the entity type representing the MongoDB document
 *
 * @author Domingos Fernando
 */
@NoRepositoryBean
public interface GenericNoSqlRepository<ENTITY extends GenericNoSqlEntity> extends ListCrudRepository<ENTITY, String>, PagingAndSortingRepository<ENTITY, String> {

    @NonNull
    Page<ENTITY> findAllByDeletedFalse(@NonNull Pageable pageable);

    @NonNull
    Optional<ENTITY> findByIdAndDeletedFalse(@NonNull String id);
}
