package io.github.isysdcore.genericAutoCrud.generics.mongo;

import jakarta.validation.constraints.NotNull;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.mongodb.repository.MongoRepository;
import org.springframework.data.mongodb.repository.Query;
import org.springframework.data.repository.NoRepositoryBean;

import java.util.Optional;

/**
 * Generic repository contract for MongoDB entities.
 *
 * <p>This interface extends the MongoDB repository infrastructure and provides
 * standard CRUD operations, pagination, sorting, and query execution
 * capabilities for the specified entity type.</p>
 *
 * <p>Repository implementations are automatically generated by Spring Data
 * MongoDB, allowing data access operations to be performed without requiring
 * manual implementation code.</p>
 *
 * @param <ENTITY> the entity type representing the MongoDB document
 * @param <ID> the identifier type of the entity
 *
 * @author Domingos Fernando
 */
@NoRepositoryBean
public interface MongoGenericRepository<ENTITY,ID> extends MongoRepository<ENTITY, ID>  {

    @NotNull
    @Override
    @Query("{ 'deleted' : false }")
    Page<ENTITY> findAll(@NotNull Pageable pageable);

    @NotNull
    @Override
    @Query("{ 'deleted' : false, 'id' : ?0 }")
    Optional<ENTITY> findById(@NotNull ID entityId);
}
